language: r

dist: trusty
sudo: false
warnings_are_errors: false

env:
  TF_VERSION="1.4"

cache:
  packages: true
  directories:
    - $HOME/.cache/pip

r_packages:
  - covr

before_script:
  - source scripts/travis_install.sh

script:
  - |
    R CMD build .
    R CMD check --no-build-vignettes --no-manual tfdeploy*tar.gz

after_failure:
  - |
    cd tests
    travis_wait 30 Rscript ../.travis.R
    sleep 2

after_success:
  - Rscript -e 'covr::codecov()'
